# Generated by Django 4.0.6 on 2022-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='capital_marker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='fias_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='kladr_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='okato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='oktmo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='population',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='tax_office',
            field=models.IntegerField(),
        ),
    ]
