# Generated by Django 4.0.6 on 2022-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_subjects_capital_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='geo_lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='geo_lon',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
