# Generated by Django 4.0.6 on 2022-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0004_delete_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('federal_district', models.CharField(max_length=255)),
                ('region_type', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('area_type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city_type', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('settlement_type', models.CharField(max_length=255)),
                ('settlement', models.CharField(max_length=255)),
                ('kladr_id', models.IntegerField()),
                ('fias_id', models.UUIDField()),
                ('fias_level', models.IntegerField()),
                ('capital_marker', models.IntegerField()),
                ('okato', models.IntegerField()),
                ('oktmo', models.IntegerField()),
                ('tax_office', models.IntegerField()),
                ('timezone', models.CharField(max_length=50)),
                ('geo_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('geo_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('population', models.IntegerField()),
                ('foundation_year', models.CharField(max_length=255)),
            ],
        ),
    ]
