# Generated by Django 4.0.6 on 2022-09-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='addres',
            new_name='address',
        ),
    ]
