# Generated by Django 4.0.6 on 2022-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_addres_subjects_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='population',
            field=models.CharField(max_length=50),
        ),
    ]
