# Generated by Django 4.0.6 on 2022-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_subjects_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='postal_code',
            field=models.CharField(max_length=50),
        ),
    ]
