# Generated by Django 4.0.6 on 2022-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_subjects_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='fias_id',
            field=models.CharField(max_length=255),
        ),
    ]
