# Generated by Django 4.0.6 on 2022-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_subjects_fias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='capital_marker',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='fias_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='kladr_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='okato',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='oktmo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='tax_office',
            field=models.CharField(max_length=255),
        ),
    ]
