# Generated by Django 4.0.6 on 2022-09-20 14:38

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_subjects_capital_marker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySeartch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse', models.CharField(max_length=255)),
                ('result_seartch', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_iso_code', models.CharField(max_length=255)),
                ('federal_district', models.CharField(max_length=255)),
                ('region_fias_id', models.CharField(max_length=255)),
                ('region_kladr_id', models.CharField(max_length=255)),
                ('region_iso_code', models.CharField(max_length=255)),
                ('region_with_type', models.CharField(max_length=255)),
                ('city_type', models.CharField(max_length=255)),
                ('city_type_full', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('settlement_type', models.CharField(max_length=255)),
                ('settlement', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_type', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('kladr_id', models.CharField(max_length=255)),
                ('fias_id', models.CharField(max_length=255)),
                ('fias_level', models.CharField(max_length=255)),
                ('capital_marker', models.CharField(max_length=255)),
                ('okato', models.CharField(max_length=255)),
                ('oktmo', models.CharField(max_length=255)),
                ('tax_office', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('geo_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('geo_lon', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
