# Generated by Django 4.0.6 on 2022-09-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_historyseartch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyseartch',
            old_name='sourse',
            new_name='source',
        ),
    ]
